version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1!
      - MSSQL_DATABASE=EnsyNetTests
    ports:
      - 1433:1433
