// <auto-generated />
using System;
using EnsyNet.DataAccess.EntityFramework.Tests.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnsyNet.DataAccess.EntityFramework.Tests.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250225184307_AddOrgPartitionedEntity")]
    partial class AddOrgPartitionedEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnsyNet.DataAccess.EntityFramework.Tests.Models.OrgPartitionedEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasFilter("DeletedAt is NULL");

                    b.HasIndex("OrgId")
                        .HasFilter("DeletedAt is NULL");

                    b.HasIndex("OrgId", "Name")
                        .HasFilter("DeletedAt is NULL");

                    b.ToTable("OrgPartitionedEntities");
                });

            modelBuilder.Entity("EnsyNet.DataAccess.EntityFramework.Tests.Models.TestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("BoolField")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("DateTimeField")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DecimalField")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DoubleField")
                        .HasColumnType("float");

                    b.Property<float>("FloatField")
                        .HasColumnType("real");

                    b.Property<Guid>("GuidField")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IntField")
                        .HasColumnType("int");

                    b.Property<string>("StringField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TimeSpanField")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasFilter("DeletedAt is NULL");

                    b.ToTable("TestEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
