name: bump-nuget-version
run-name: Ensy Net Core - Bump NuGet Version on Release

on:
  pull_request:
    branches:
      - main
  release:
    types: [published]

permissions:
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from name
        id: nuget_version
        run: |
          #title='${{ github.event.release.name }}'
          title='v0.0.4'
          regex='.*v([0-9]+\.[0-9]\.[0-9]+(-[0-9]+)?).*'

          [[ $title =~ $regex ]] || echo "No version could be found in release title."

          version=${BASH_REMATCH[1]}
          if [[ -z $version ]]; then 
            exit 1
          fi

          echo "Found version: $version"
          echo "nuget_version=$version" >> "$GITHUB_ENV"

      - name: Print name
        run: |
          echo "Found version: ${{ env.nuget_version }}"

      
