name: bump-nuget-version
run-name: Ensy Net Core - Bump NuGet Version on Release

on:
  pull_request:
    branches:
      - main
  release:
    types: [published]

permissions:
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from name
        id: nuget_version
        shell: pwsh
        run: |
          '${{ github.event.release.name }}' -match '.*v([0-9]+\.[0-9]\.[0-9]+(-[0-9]+)?).*'
          'v0.0.4' -match '.*v([0-9]+\.[0-9]\.[0-9]+(-[0-9]+)?).*'
          $version = $Matches.1
          echo "Found version: $version"
          "nuget_version=$version" >> "$GITHUB_ENV"

      - name: Print name
        shell: pwsh
        run: |
          echo "Found version: ${{ env.nuget_version }}"

      
