name: ensy-net-core
run-name: Ensy Net Core packaging
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
    versioning:
        runs-on: ubuntu-latest
        needs: [ci]
        steps:
            - uses: actions/checkout@v4
    package:
        runs-on: ubuntu-latest
        needs: [versioning]
        steps:
            - uses: actions/checkout@v4
